# Site settings
title: Tenants Rights
subtitle: Helping you rent easier...
email: 
description: 
url: http://iinf362.github.io/team5/
github_username:

menu:
	News: front-page.html
	Documents: default-page.html

# Build settings
markdown: kramdown
permalink: pretty